### ISSUE TITLE
Potential attack vector

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity-bridge#54]
Current version of the Bridge doesn't charge users for making withdraws so that Authorities running the Bridge have to cover all costs. This potentially allows an attacker to deplete Authorities’ funds.

## Potential solution (proposed by @debris ):
Withdraws should not be free for users. The exact amount of gas that is spent on a withdraw should be measured and charged to users. It's a simple feature which could be added to function `transfer()` of `ForeignBridge` smart contract. Truffle tests should be written and run. Truffle tests for foreign contract are located in `truffle/test/foreign.js`.

**Comment by snd** [comment]
@bjornwgnr i'll look into implementing a fix tomorrow. should be fairly straightforward

some notes on this:

# attack

for the attack to work the attacker must have balance on  `ForeignBridge`.

the attacker repeatedly calls `ForeignBridge.transfer(recipient, value)` with very small `value` (`1`).
this costs very little gas to the attacker.

authorities have to spend much higher amounts of gas to relay the withdrawal:

```
costPerAuthority = gasCost(ForeignBridge.submitSignature)

totalCost = requiresSignatures * costPerAuthority + gasCost(HomeBridge.withdraw)
```

the attacker can currently spend `1` wei worth of balance on `ForeignBridge` to drain all authorities
balances by several orders of magnitude more wei.

# solution

in `ForeignBridge.transfer(recipient, value)` reduce balance on `ForeignBridge` not just by `value`
but by `value + totalCost`.

the `totalCost` could be divided among all current authorities and added to their balance on `ForeignBridge` to pay for the relay.

now the attacker pays for all the costs that occur to the authorities during the relay.

that would prevent this attack from being feasable since the attacker now pays the authorities for their costs.

an attacker with more funds than an authority could still deplete an authorities funds and potentially break the bridge. that's a different far more rare and unlikely scenario though

**Comment by snd** [comment]
started working on this over here https://github.com/paritytech/parity-bridge/pull/56

**Comment by snd** [comment]
> Current version of the Bridge doesn't charge users for making withdraws

calling `transfer` still costs gas of course

if i'm not mistaken the attack boils down to:

**an attacker can spend 1x to deplete `requiredSignatures` funds by at least 3x**

updated the above comment

**Comment by snd** [comment]
i think deposits are vulnerable to this depletion attack as well:

an attacker could call `HomeBridge.()` (fallback function) with value `1` wei which would cost it `22393` gas.

`requiredSignatures` count authorities would then spend `91231` gas each which is the cost of `ForeignBridge.deposit`.

this seems worse since an attacker could spend 1x to deplete the authorities by ~4x

**Comment by snd** [comment]
@debris @bjornwgnr should we add a cost to deposits as well?

**Comment by snd** [comment]
i thought more generally about authorities funds and gas costs:

authorities pay for all the relay gas costs. authorities should never run out of funds. authorities should never need "topping up". users/senders should pay upfront for all gas costs incurred in the relay.

rather than reducing tokens on foreign_chain (as currently implemented https://github.com/paritytech/parity-bridge/blob/06279ce6a46b3edb50b1fa9c5a73a1c4b5851637/contracts/bridge.sol#L270) we should require the sender of a `transferToHomeChain` transaction to send a value equal to the relay gas cost and redistribute that directly to authority accounts.

similar for deposit: on `HomeBridge.()` subtract relay gas cost from sent value, divide it and transfer it to all of the authorities.

this way authorities should never run out of funds

**Comment by rphmeier** [comment]
> a value equal to the relay gas cost
this is unpredictable without a fixed gas price, in which case the validators would be overpaying if the network is mostly empty and the bridge may not work if the network is congested

**Comment by rphmeier** [comment]
also, the fee should be deposited into the account of the authority who actually made the transaction on the chain, not split evenly. otherwise that validator is getting back less than he is spending and the others get back something for doing nothing.

**Comment by snd** [comment]
@bjornwgnr talked with @rphmeier in person about this. he had some valuable input.

the current bridge code is based on the assumption that authorities have unlimited funds and pay for all the gas costs. this is not the case if `home_chain` is the ethereum main chain.

this problem is more involved than it originally seemed!

i'll give you an update on monday

**Comment by snd** [comment]
we can, for now, assume that authorities have unlimited funds on the  `foreign_chain` i.e. can do zero-fee transactions, since they are the authorities. we don't need to deal with gas costs of deposits right now. for deposits authorities only do transactions on `foreign_chain`.

for withdrawals only the final`withdraw` transaction is relevant in the context of this issue. it's the only transaction that authorities do on the `home_chain`.

**Comment by bjornwgnr** [comment]
@snd thx for the update!

**Comment by snd** [comment]
for the withdrawal @rphmeier suggested a solution that is similar to how Aura works:

https://github.com/paritytech/parity/wiki/Aura

`authorities` is the list of authorities.

`authorities.length` is the number of authorities.

`blocks_per_step` is the step duration in blocks.

the current `step` is `block.number % blocks_per_step`.

the `primary_authority` for step `step` is `authorities[authorities.length % step]`.

the `primary_authority` is responsible for relaying withdrawals (by calling `HomeBridge.withdraw` for each *finalized* `foreign_bridge.CollectedSignatures` event).

only the `primary_authority` is allowed to call `HomeBridge.withdraw`.

this would also resolve https://github.com/paritytech/parity-bridge/issues/64:
if the `primary_authority` is malicious and doesn’t call `HomeBridge.withdraw` then on the next step the next `primary_authority` has a chance.
eventually `HomeBridge.withdraw` will get called. relays won’t get stuck.

as implemented right now, only one call to `HomeBridge.withdraw` is allowed per operation hash (`transactionHash` of the withdraw on `foreign_chain`).

### incentive

we can, for now, assume that authorities have unlimited funds on the `foreign_chain` i.e. can do zero-fee transactions, since they are the authorities.

transactions on `home_chain` cost gas.
calling `HomeBridge.withdraw` costs gas.

what’s the incentive of an authority to call withdraw and spend gas?
being an honest authority is not attractive if it means constantly loosing money on gas costs.
authority should get a compensation that is roughly equal to the gas cost.

### idea for a solution

dynamically within `HomeBridge.withdraw` calculate `estimatedWeiCostOfWithdraw` of `HomeBridge.withdraw` as `estimatedGasCostOfWithdraw * tx.gasprice`.

transfer `value - estimatedWeiCostOfWithdraw` to recipient where `value` is the value of the withdraw.

transfer `estimatedWeiCostOfWithdraw` to `primary_authority.

this way the `recipient` pays the `primary_authority` for the gas costs.

#### what if `value < estimatedWeiCostOfWithdraw`?

then there’s no incentive to call `HomeBridge.withdraw`

`primary_authority` could estimate `estimatedWeiCostOfWithdraw` and `value < estimatedWeiCostOfWithdraw` before calling `HomeBridge.withdraw` and decide not to call `HomeBridge.withdraw`.

we could put the burden on the user/recipient and say: “if you withdraw less than x then your withdraw might not complete”. x could be based on some upper bound on the gas price for a while (don't know if that's possible). alternatively the user could be required to check/assert `value > estimatedGasCostOfWithdraw * currentGasPriceOnHomeChain` before each withdraw.

**would this be acceptable?**

a future `primary_authority` might still call `HomeBridge.withdraw` for that withdraw if `tx.gasprice` becomes lower.

**Comment by snd** [comment]
i'll add more notes to this in the next couple of hours

**Comment by snd** [comment]
@debris if you have a moment could you take a look at my last comment? any problems with that solution? if not i'd start on an implementation :)

**Comment by debris** [comment]
> @debris @bjornwgnr should we add a "relay cost" to deposits as well?

I don't think so. Let's keep it simple for now and assume that transaction on the foreign chain are always free.

> the current bridge code is based on the assumption that authorities have unlimited funds and pay for all the gas costs. this is not the case if `home_chain` is the ethereum main chain.

I don't think we need to change this assumption for now. If authority runs out of funds on the main chain, nothing bad happens. It only stops relaying transactions. It doesn't break the network, cause the network can recover to the latest state at any time when the account is top up. We only need to make it easy for an authority to manually (or even automatically) claim ether charged in fees for relaying withdraws. 

I think we should start with a simple implementation and later on think about solution utilizing `estimatedGasCostOfWithdraw`.

**Comment by snd** [comment]
@debris thanks for the feedback

consider all but my last comment (https://github.com/paritytech/parity-bridge/issues/54#issuecomment-351009494) as deprecated. my mental model of POA and the bridge needed some adjustment ; )

> I think we should start with a simple implementation

i'd love your feedback on this:
https://github.com/paritytech/parity-bridge/issues/54#issuecomment-351009494

it's fairly simple and imho solves the problem

**Comment by debris** [comment]
Ok, let's implement `estimatedGasCostOfWithdraw`.

> we could require authorities to call something like `ForeignBridge.ignoredWithdraw(transactionHash)` in case they ignore a withdraw because of insufficient value. this would record their decision and enable everyone to distinguish honest and malicious/faulty authority behaviour. otherwise it's unclear whether an authority ignored a withdraw honestly or our of malice.

Despite it's a foreign chain, I would still prefer the authorities to do nothing if it wasn't paid for.

The idea, looks really good. Sorry that it took so long for me to comment on it :)

**Comment by snd** [comment]
OK, i'll implement the fix tomorrow

**Comment by snd** [comment]
resolved in https://github.com/paritytech/parity-bridge/pull/77
