### ISSUE TITLE
Cannot transfer funds back to home via relay

### ISSUE THREAD

**Issue by akolotov** [paritytech/parity-bridge#87]
cloned the project from the latest git and built the binary, ran 2 PoA networks and ran bridge.

Performing the following steps:

1. Deposit some funds to the home contract.
2. Check that Deposit events on both sides appeared.
3. Check the balance of the account on the foreign contract 
4. Execute "transferHomeViaRelay"
5. Check that Withdraw event appeared on the foreign side
6. Check that CollectedSignatures event appeared on the foreign side

After that the birdge is terminated with the message
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `160`,
 right: `84`: ForeignBridge never accepts messages with len != 84 bytes; qed', bridge/src/bridge/withdraw_relay.rs:60:1
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
and there is no Withdraw event on the home side.

**Comment by snd** [comment]
thanks for finding. i'll look into it

**Comment by snd** [comment]
finally got an initial deposit/withdraw integration test to run (tricky).

was able to reproduce this. working on a fix now

**Comment by snd** [comment]
output from integration test that reproduces the problem is here: https://travis-ci.org/paritytech/parity-bridge/jobs/331185715#L1753

found a temporary fix. working on finding the root cause

**Comment by snd** [comment]
here's the most current travis log that reproduces the problem:
https://travis-ci.org/paritytech/parity-bridge/jobs/331754192#L1766

here's a temporary fix (makes some other tests fail though):
https://github.com/paritytech/parity-bridge/pull/95/commits/ef3cb877acb3f5fe99e3b0e0a81e2c2084c8fd1c

the problem is the following:

https://github.com/paritytech/parity-bridge/blob/ef3cb877acb3f5fe99e3b0e0a81e2c2084c8fd1c/bridge/src/bridge/withdraw_relay.rs#L192

`messages_raw` and `signatures_raw` contain `Bytes` with length `160`.
the code expects length `84` for the messages and length `65` for the signatures.
the messages and signatures are at offset `64` in the `Bytes` of length `160` however.

the temporary fix is to slice messages and signatures out of the `160` bytes long results.

@debris any ideas why this is happening and how to fix it? i'm not super familiar with the rust side of the codebase yet.

**Comment by snd** [comment]
@akolotov this should be fixed on master. it would be great if you could run the steps again and confirm that it works for you now.

**Comment by akolotov** [comment]
Tested. `withdraw_relay` works now. Thank you.
