### ISSUE TITLE
gas spent even if there is no necessity to cover relay expenses

### ISSUE THREAD

**Issue by akolotov** [paritytech/parity-bridge#90]
https://github.com/paritytech/parity-bridge/blob/1cef1596a48edbf360833e23420e4d76020d8f75/contracts/bridge.sol#L253-L254

Let's imagine a configuration when `estimatedGasCostOfWithdrawParam` is zero. It will cause that zero funds will be tried to transfer to `msg.sender` in L253-L254. Could it be optmized to avoid gas spending in case of zeroed `estimatedGasCostOfWithdrawParam`?

**Comment by snd** [comment]
we could wrap the statement in an `if (estimatedWeiCostOfWithdraw != 0)`. that might use less gas in case when `estimatedGasCostOfWithdrawParam == 0`.

before doing this change one should proof that the optimization actually uses less gas (by computing/estimating gas for both solutions) and that the difference in gas use is significant enough to justify the increase increasing the complexity of the code.

**Comment by akolotov** [comment]
Ok. I have performed few experiments in Remix.

```
function A(address recipient, uint value) public {
    if (value != 0) {
        recipient.transfer(value);
    }
}
```
- `A("0xca35b7d915458ef540ade6068dfe2f44e8fa733c", 500000000000000)` consumes 7724 gas
- `A("0xca35b7d915458ef540ade6068dfe2f44e8fa733c", 0)` consumes 225 gas

```
function A(address recipient, uint value) public {
    recipient.transfer(value);
}
```
- `A("0xca35b7d915458ef540ade6068dfe2f44e8fa733c", 500000000000000)` consumes 7695 gas
- `A("0xca35b7d915458ef540ade6068dfe2f44e8fa733c", 0)` consumes 995 gas

As you can see that really difference in case of 0 ether sent is 770 gas. It is not big really. And with the current ether price it is about more than 1.5 cents. But times change and it could be changed as well. So, it is more about good style rather than real economy. It will not increase complexity much anyway.

**Comment by snd** [comment]
> Let's imagine a configuration when estimatedGasCostOfWithdrawParam is zero

wouldn't you only use that kind of configuration if you didn't care about gas prices on home anyway?
wouldn't this kind of optimization be unnecessary then?

the change would increase gas for the normal case (`estimatedWeiCostOfWithdraw != 0`) by `29` while decreasing it for a special configuration (`estimatedWeiCostOfWithdraw == 0`) by `770`.

closing this for now because i think it's too early for microoptimizations like this!

the bridge will likely change a lot.
microoptimizations done at this point will likely grow obsolete.

when the bridge is relatively stable and we know it won't change too much, then we might profile and optimize.
