### ISSUE TITLE
Rearrangement for configuration parameter estimated_gas_cost_of_withdraw 

### ISSUE THREAD

**Issue by akolotov** [paritytech/parity-bridge#92]
https://github.com/paritytech/parity-bridge/blob/1cef1596a48edbf360833e23420e4d76020d8f75/examples/config.toml#L1

Since `estimated_gas_cost_of_withdraw` is related to operations occuring on the home side, this parameter should be included in the section `[home]`.

**Comment by snd** [comment]
we had a short internal discussion about this at the time.

currently both the `home` and `foreign` sections get parsed as a `Node` config struct as they currently share all fields. rather than having two separate `HomeNode` and `ForeignNode` structs or adding optional fields to `Node` we chose to add `estimated_gas_cost_of_withdraw` at the toplevel.

imho this is fine for now. in the future, when the bridge will have changed quite a bit, we'll most likely rethink and refactor the config module entirely.

**Comment by snd** [comment]
closing this as it no longer applies after merging https://github.com/paritytech/parity-bridge/pull/114. `estimated_gas_cost_of_withdraw` is now used on both sides.
